Open the .github/workflows/workflow.yml file and add the following:

name: CI workflow
workflow triggers: push on main branch and pull_request on main branch
Jobs
runs-on: ubuntu-latest
container: python:3.9-slim
Checkout step:
name: Checkout
uses: actions/checkout@v3
Install Dependencies step:
name: Install dependencies
run python -m pip install --upgrade pip and pip install -r requirements.txt commands
name: Lint with flake8
commands:
flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
name: Run unit tests with nose
command:
nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
